dist: trusty
sudo: false

language: java
jdk: openjdk8

# TODO: Database setup or should we mock database in tests? Probably yes.
# services:
#   - postgresql

before_script:
  - cd 'backend/skeleton'
# - psql -c ./src/main/resources/TestDB.sql -U postgres

after_success:
  - mvn clean cobertura:cobertura coveralls:report
